"""drop pipeline_logs table, logs go to a file instead

Revision ID: 1e008927ddca
Revises: a6a5864dad63
Create Date: 2026-09-22 12:59:54.042189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e008927ddca'
down_revision: Union[str, Sequence[str], None] = 'a6a5864dad63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_logs_created_at'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_entity_slug'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_event'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_run_id'), table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('entity_slug', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_logs_pkey'))
    )
    op.create_index(op.f('ix_pipeline_logs_run_id'), 'pipeline_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_event'), 'pipeline_logs', ['event'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_entity_slug'), 'pipeline_logs', ['entity_slug'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_created_at'), 'pipeline_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
