"""drop tender_records and tender_record_tags - tenders stay file-based

Revision ID: 4fe54e42c4be
Revises: 1e008927ddca
Create Date: 2026-09-22 16:08:46.057716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe54e42c4be'
down_revision: Union[str, Sequence[str], None] = '1e008927ddca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_record_tags_tender_record_id'), table_name='tender_record_tags')
    op.drop_index(op.f('ix_tender_record_tags_tender_tag_id'), table_name='tender_record_tags')
    op.drop_table('tender_record_tags')
    op.drop_index(op.f('ix_tender_records_classification'), table_name='tender_records')
    op.drop_index(op.f('ix_tender_records_entity_slug'), table_name='tender_records')
    op.drop_index(op.f('ix_tender_records_run_id'), table_name='tender_records')
    op.drop_table('tender_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_no', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('published_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('closing_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extracted_at', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('classification', postgresql.ENUM('pending', 'done', 'error', name='tender_classification'), autoincrement=False, nullable=False),
    sa.Column('classify_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tender_records_pkey')),
    sa.UniqueConstraint('run_id', 'content_hash', name=op.f('uq_tender_records_run_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tender_records_run_id'), 'tender_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_tender_records_entity_slug'), 'tender_records', ['entity_slug'], unique=False)
    op.create_index(op.f('ix_tender_records_classification'), 'tender_records', ['classification'], unique=False)
    op.create_table('tender_record_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tender_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tender_tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tender_record_id'], ['tender_records.id'], name=op.f('tender_record_tags_tender_record_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_tag_id'], ['tender_tags.id'], name=op.f('tender_record_tags_tender_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tender_record_tags_pkey')),
    sa.UniqueConstraint('tender_record_id', 'tender_tag_id', name=op.f('uq_tender_record_tags'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tender_record_tags_tender_tag_id'), 'tender_record_tags', ['tender_tag_id'], unique=False)
    op.create_index(op.f('ix_tender_record_tags_tender_record_id'), 'tender_record_tags', ['tender_record_id'], unique=False)
    # ### end Alembic commands ###
