"""tender records, tag links, pipeline logs

Revision ID: a6a5864dad63
Revises: 891807d3c007
Create Date: 2026-09-22 12:53:43.028680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a5864dad63'
down_revision: Union[str, Sequence[str], None] = '891807d3c007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('entity_slug', sa.String(length=200), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_logs_created_at'), 'pipeline_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_entity_slug'), 'pipeline_logs', ['entity_slug'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_event'), 'pipeline_logs', ['event'], unique=False)
    op.create_index(op.f('ix_pipeline_logs_run_id'), 'pipeline_logs', ['run_id'], unique=False)
    op.create_table('tender_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('entity_slug', sa.String(length=200), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('office', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_no', sa.String(length=300), nullable=True),
    sa.Column('published_date', sa.String(length=100), nullable=True),
    sa.Column('closing_date', sa.String(length=100), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('document_links', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.String(length=40), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.Enum('pending', 'done', 'error', name='tender_classification'), nullable=False),
    sa.Column('classify_reason', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'content_hash', name='uq_tender_records_run_hash')
    )
    op.create_index(op.f('ix_tender_records_classification'), 'tender_records', ['classification'], unique=False)
    op.create_index(op.f('ix_tender_records_entity_slug'), 'tender_records', ['entity_slug'], unique=False)
    op.create_index(op.f('ix_tender_records_run_id'), 'tender_records', ['run_id'], unique=False)
    op.create_table('tender_record_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_record_id', sa.Integer(), nullable=False),
    sa.Column('tender_tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_record_id'], ['tender_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_tag_id'], ['tender_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_record_id', 'tender_tag_id', name='uq_tender_record_tags')
    )
    op.create_index(op.f('ix_tender_record_tags_tender_record_id'), 'tender_record_tags', ['tender_record_id'], unique=False)
    op.create_index(op.f('ix_tender_record_tags_tender_tag_id'), 'tender_record_tags', ['tender_tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_record_tags_tender_tag_id'), table_name='tender_record_tags')
    op.drop_index(op.f('ix_tender_record_tags_tender_record_id'), table_name='tender_record_tags')
    op.drop_table('tender_record_tags')
    op.drop_index(op.f('ix_tender_records_run_id'), table_name='tender_records')
    op.drop_index(op.f('ix_tender_records_entity_slug'), table_name='tender_records')
    op.drop_index(op.f('ix_tender_records_classification'), table_name='tender_records')
    op.drop_table('tender_records')
    op.drop_index(op.f('ix_pipeline_logs_run_id'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_event'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_entity_slug'), table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_created_at'), table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    # ### end Alembic commands ###
